name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: npm i
    - run: cd frontend
    - run: npm i
    - run: npm i react-scripts
    - run: npm run build
    - run: cd ..
    - run: pm2 stop 0
    - run: pm2 start 0
    - run: pm2 save
    - run: sudo service nginx restart
